### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by bboydt** [dalethomas81/HamMessenger#3]
We need to know what versions of the libraries to use. Also, compiling instructions would be helpful.

**Comment by dalethomas81** [comment]
Hey @TildeOrange! Thanks for pointing this out. I have added the information you requested. Can you check out these 2 links in the readme and if this meets the requirement then we can close this one out.

https://github.com/dalethomas81/HamMessenger#libraries
https://github.com/dalethomas81/HamMessenger#compilation

**Comment by bboydt** [comment]
Looks good
